### ISSUE TITLE
com.android.ddmlib.ShellCommandUnresponsiveException

### ISSUE THREAD

**Issue by 1ak31sha** [bitrise-steplib/steps-start-android-emulator#25]
I am getting this error about 25% of the time
Here is a build that got the error https://www.bitrise.io/build/d3eddc812fb2833e

i checked this SO question...http://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception

Is this a problem with the emulators on bitrise and if so what can i do to stop the flaky error?
Let me know if more info needed, happy to provide

**Comment by viktorbenei** [comment]
Thanks for reporting @kpogz - @godrei pls check this!

**Comment by godrei** [comment]
Hi @kpogz ,
did you try to enable longer timeout in adb options, like [here](https://github.com/googlemaps/android-maps-utils/commit/da8b766ef770544f79120a2aba60f70dabd47b18#diff-0d1d9100a9b6813b8cb5c470bf313d00R41)

(Mentioned in the SO question, you linked.)

**Comment by 1ak31sha** [comment]
ah thanks, missed that. i ran the test with it last night. only 10% failed vs 25%...will try further increasing the timeout!

**Comment by godrei** [comment]
Great to hear that, i will close this issue, if you think, that we could do more to help you solve this issue, feel free to open it again.

**Comment by 1ak31sha** [comment]
hmm, its actually still happening alot. maybe got lucky that time with the 10%. please re-open!

**Comment by vikingden8** [comment]
hi,guys:
like ddmlib doc says: Exception thrown when a shell command executed on a device takes too long to send its output.The command may not actually be unresponsive, it just has spent too much time not outputting any thing to the console.
I think if your command really take long time to execute, your should set adb command execution timeout to 0. and ShellCommandUnresponsiveException will never throw out.
I found this in [AdbHelper](https://android.googlesource.com/platform/tools/base/+/0c58ef3a3a25e7eb4813825899f2758e035039a5/ddmlib/src/main/java/com/android/ddmlib/AdbHelper.java) documentation, take a look this method:

```
static void executeRemoteCommand(InetSocketAddress adbSockAddr, String command, IDevice device, IShellOutputReceiver rcvr, int maxTimeToOutputResponse) throws TimeoutException, AdbCommandRejectedException, ShellCommandUnresponsiveException, IOException {...}
```

**Comment by trapacska** [comment]
Hey!

As far as I could research, `com.android.ddmlib.ShellCommandUnresponsiveException` throwing was after a hardcoded timeout value by gradle, and they fixed it since the version 2.0. Going further I've figured out that mostly nothing you can set from adb command line, avoiding this exception requires extra code in the project itself.

This is the main reference I've found btw:
https://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception/28949723

There is an ENV that could be set also: `ADB_INSTALL_TIMEOUT`, however If I understand well, you did not have any issue with installing the APK but running other commands. Isn't it? :)

**Comment by trapacska** [comment]
@vikingden8 : did you managed to fix this issue? Did you found anything we need to change in the step?

**Comment by trapacska** [comment]
I close this issue for now, as for me it seems like this issue is not related to the step itself. Please feel free to re-open this issue if you think it is not right or if you encounter any issues!

**Comment by TheMandalorianHub** [comment]
when clear logcat ,that exception jump out always

**Comment by fehersanyi-bitrise** [comment]
Hy @xiaochenu 👋

Could you please define your issue in a little bit more detail? 🙃
So I'm sure that I understand you and can help you out.

**Comment by Zebiano** [comment]
I've been having the same problem as @xiaochenu lately @fehersanyi-bitrise . Whenever I have Logcat open, and try to clean it (Right-click -> Clear Logcat) it freezes for some seconds, gives me this error and then cleans the Logcat. It's just a bit annoying to wait that extra time and then having to hit "Ok" to accept the error message.

**Comment by bismarabia** [comment]
I'm having the same issue, when I click on clear Logcat button a popup with com.android.ddmlib.ShellCommandUnresponsiveException exception.

any update on this?
