### ISSUE TITLE
Missing GitHub PR check

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-start-android-emulator#33]
Current HEAD (2d53e954bc7ea1d0fbde9fdda6e64e6a1b301de9) does not pass ci workflow. Here is what I get on Linux stack.
```
+ errcheck -asserts=true -blank=true _/bitrise/src
cannot find package "_/bitrise/src" in any of:
	/usr/local/go/src/_/bitrise/src (from $GOROOT)
	/go/src/_/bitrise/src (from $GOPATH)
error: failed to check packages: could not type check: no initial packages were loaded
```
Command reproducing this issue:
```
docker run --privileged -ti --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/docker-android:latest bitrise run ci
```

Additionally, no bitrise build is triggered on pull requests (or at least results are not posted to GitHub), eg. #32 has no checks.

**Comment by viktorbenei** [comment]
@koral-- PRs are triggered but we messed up the github status connection in this Org, will fix it asap

> does not pass ci workflow

It does, but as this is a Go package, you have to `git clone` it into `$GOPATH/src/github.com/bitrise-steplib/steps-start-android-emulator`, or else the go tools won't work. (This is a Go limitation, you have to work in a Go "Workspace" or else most tools won't work. AFAIK this limitation will be removed in Go 1.9 or 1.10. If you don't have a configured GOPATH, then it's simply just `$HOME/go`, that's the default, so `$HOME/go/src/github.com/bitrise-steplib/steps-start-android-emulator` for example).

**Comment by viktorbenei** [comment]
@godrei @trapacska pls check the GitHub PR status connections!!

**Comment by koral--** [comment]
> It does, but as this is a Go package, you have to git clone it into $GOPATH/src/github.com/bitrise-steplib/steps-start-android-emulator,

OK, thx. I've adjusted issue title to reflect only not working PR check.

**Comment by viktorbenei** [comment]
Thanks @koral-- we'll fix that ASAP! 😉

**Comment by trapacska** [comment]
Fixed, thanks @koral-- ! 😊🎉🚀
