### ISSUE TITLE
Unable to run emulator using ABI other than armeabi-v7a

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-start-android-emulator#38]
Right now Create and Start Android Emulator steps supports only armeabi-v7a (32-bit) however, support for other ABIs can be easily added. The most important is arm64-v8a but mips can also work. x86(_64) too but not on bitrise.io due to lack of KVM.
This a quite significant change so I would like to ask before sending PRs.

Here is my solution:
- [unlock abi input parameter in steps-create-android-emulator](https://github.com/DroidsOnRoids/steps-create-android-emulator/commit/ff6c3480873d86c1289ef7b14823b8a26a56d8a1)
- [adjust LD_LIBRARY_PATH and use emulator binary in go-android](https://github.com/DroidsOnRoids/steps-start-android-emulator/commit/ca0b178c0e1e7a63e367002b8c64dc96f5984396) - this is currently modified in steps-start-android-emulator repo just for testing purposes

steps-start-android-emulator does not need to be modified apart from adding tests with emulators with new ABIs

What do you think?

**Comment by viktorbenei** [comment]
I'd say it's a great idea - is there any perf improvement with those ABIs? Or is this more for just the sake of "completeness"?

@godrei & @trapacska WDYT?

**Comment by koral--** [comment]
armeabi-v8a is 64-bit so it matters when project contains native (C/C++/assembly) sources. E.g. `sizeof(int)` is 8 bytes instead of 4 in armeabi-v7a. It is useful to test such apps on that target. Especially since modern devices has 64-bit ARM CPUs (Nexuses starting from 5X/6P, Samsung Galaxy since S6 etc.) and they has significant market share.
Other ABIs has less practical meaning e.g. there were only a few released MIPS devices several years ago. x86 does not work on bitrise.io so may be only useful when running locally.

**Comment by viktorbenei** [comment]
@koral-- I agree, was just curious whether other emulators/ABIs would be a bit faster. But even if not, supporting those is indeed required 👍 :)

**Comment by koral--** [comment]
I don't think that 64-bit emulator itself will be faster than 32-bit.

**Comment by viktorbenei** [comment]
Sure, no problem, I just hoped it might :)

**Comment by koral--** [comment]
Relevant steps have been updated so it seems that this issue is resolved.

**Comment by viktorbenei** [comment]
Thanks @koral-- ! :)
