### ISSUE TITLE
Emulator SDK package installation

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-start-android-emulator#40]
Starting from SDK Tools 25.3.0 it is possible to have properly installed tools without an emulator (https://developer.android.com/studio/releases/sdk-tools.html). That's because it is no longer preinstalled. See https://github.com/bitrise-docker/android/pull/96#discussion_r127255480 for more info.
On unmodified stack from bitrise.io such case should not occur because the emulator package is explicitly installed. 
Perhaps this step should check if emulator command is available and try to install it if not? Such situation may occur when using bitrise CLI locally.

**Comment by viktorbenei** [comment]
Definitely! Just one note:

> On unmodified stack from bitrise.io such case should not occur because the emulator package is explicitly installed.

Not on the LTS stack, that should always be kept in mind ;)

Otherwise 👍

**Comment by koral--** [comment]
Correct me if I'm wrong but LTS stack contains SDK tools 24.4.1, according to this: https://github.com/bitrise-docker/android/blob/b910acf7019be93207459c7735d0e2dfbed63be9/Dockerfile#L21
so it also contains emulator.

**Comment by viktorbenei** [comment]
That's true, it definitely does.
