### ISSUE TITLE
Continually getting "Checking for started device serial..."

### ISSUE THREAD

**Issue by tomcurran** [bitrise-steplib/steps-start-android-emulator#42]
1.3.x worked on 2017.10.30, didn't work from 2017.11.06 (I've not got any builds in between these dates to confirm exact day). I've had to downgrade to 1.2.1 which does work right now. I'm guessing an environment change has caused this.

**Comment by erosdome** [comment]
Hi, thanks for reporting the issue, we will be looking into it ASAP.

**Comment by viktorbenei** [comment]
Hi @tomcurran and sorry for the delay.

We need more information about this - please create a build issue report at https://discuss.bitrise.io/c/issues/build-issues so that we have all the details we need for reproduction and fixing it :)
