### ISSUE TITLE
Getting an Emulator to boot

### ISSUE THREAD

**Issue by tobrun** [bitrise-steplib/steps-start-android-emulator#7]
When adding the `Start Android Emulator` as a workflow step on `Bitrise`.

It is currently not clear what should be inserted in `Emulator to boot`:

> <img width="766" alt="screen shot 2015-12-04 at 12 27 29" src="https://cloud.githubusercontent.com/assets/2151639/11588641/6b746c96-9a82-11e5-8c50-2885b8a30278.png">

After some googling I found out [this tip and trick on emulators](http://devcenter.bitrise.io/docs/android-tips-and-tricks#section-emulators).

> <img width="772" alt="screen shot 2015-12-04 at 12 25 37" src="https://cloud.githubusercontent.com/assets/2151639/11588638/5ebf3846-9a82-11e5-83e2-65a2a1d33c1c.png">

This resulted in following timeout in my build:

<img width="795" alt="screen shot 2015-12-04 at 12 30 07" src="https://cloud.githubusercontent.com/assets/2151639/11588706/d15a6074-9a82-11e5-8e3e-c951e05ec541.png">

**Comment by viktorbenei** [comment]
Thanks for the feedback! Indeed, this step is not yet production ready, we're still working on the "UX" of the step.

For reference, while we're working on fixing this (allowing the step to create it's own emulator) you can create an Android Emulator with a Script step, just follow this guide/description: http://devcenter.bitrise.io/v1.0/docs/android-tips-and-tricks#section-emulators

**Comment by viktorbenei** [comment]
To reflect on the name issue: make sure that the name you specify when you create the emulator (the `-n` parameter) is the one you specify for this script!

**Comment by tobrun** [comment]
Thank you @viktorbenei,

I was already investigation your suggestion on my own:
In bottom right you can see the creation of the AVD:

<img width="1090" alt="screen shot 2015-12-04 at 13 12 34" src="https://cloud.githubusercontent.com/assets/2151639/11589431/bca275d0-9a88-11e5-866d-6360e088bbd8.png">

Now in my `Start Android Emulator`, I have configured using 'test':

<img width="1125" alt="screen shot 2015-12-04 at 13 13 43" src="https://cloud.githubusercontent.com/assets/2151639/11589440/e6bd51dc-9a88-11e5-8dca-febe420982ff.png">

This results in following output:

Create AVD step:
<img width="1194" alt="screen shot 2015-12-04 at 13 15 18" src="https://cloud.githubusercontent.com/assets/2151639/11589469/186ba83c-9a89-11e5-9914-d9441b4d22b8.png">

Start Android Emulator step:
<img width="774" alt="screen shot 2015-12-04 at 13 15 02" src="https://cloud.githubusercontent.com/assets/2151639/11589471/241ca0fa-9a89-11e5-8e69-61c2467a4fb7.png">

Not really sure why it is not working, Any ideas?

**Comment by viktorbenei** [comment]
Ouch, it seems we forgot to create a new version.. Here's what changed since `0.9.1` - I believe these changes should fix this issue: https://github.com/bitrise-io/steps-start-android-emulator/compare/0.9.1...master

If you could test & confirm with the current `master` branch version, we would release a new version ASAP.

To test with the `master` branch version:
1. Open your workflow, in `bitrise.yml` mode
2. Replace the `- start-android-emulator@0.9.1:` line with: `- git::https://github.com/bitrise-io/steps-start-android-emulator.git@master:`
3. Save it & start a new build or hit a "rebuild" on bitrise.io

_Note: you might want to create a backup of your `bitrise.yml` before you would change it. You can simply copy-paste the content of the `bitrise.yml` from bitrise.io, save it to a file, and if you have to import it back just copy-paste the content and hit save on bitrise.io_

**Comment by tobrun** [comment]
@viktorbenei 

After applying you suggestion above, I'm getting:

<img width="1282" alt="screen shot 2015-12-04 at 13 51 47" src="https://cloud.githubusercontent.com/assets/2151639/11590110/4668616c-9a8e-11e5-9ba4-da2555134bb7.png">

**Comment by viktorbenei** [comment]
@godrei will check it ASAP and help you with the setup / required fixes in the step

**Comment by viktorbenei** [comment]
@tobrun we just updated the `master` branch, can you try it again?

**Comment by viktorbenei** [comment]
For some reason one of the `emulator` calls failed with an obscure error, that it can't determine the bitness of the system, and that we have to force it to be 32 bit -> for now we added this `-force32bit` flag, we'll try to find what might cause this issue. Right now this seems to work both on Linux/Docker and on Mac OS X.

**Comment by viktorbenei** [comment]
If you can confirm that this works for you too @tobrun we'll release a new version of this step and you can switch back from the `master` branch.

**Comment by tobrun** [comment]
I can confirm that I was able to boot the emulator! Great job you guys.

**Comment by tobrun** [comment]
@viktorbenei 
![screenshot_20151204-184952](https://cloud.githubusercontent.com/assets/2151639/11598263/224a8e44-9ac1-11e5-8700-f33ac25bc87d.png)

Let me know when I can switch back to the default step, will test again and close this issue.

**Comment by viktorbenei** [comment]
We'll release a new version tomorrow, I'll let you know when it's ready!

**Comment by viktorbenei** [comment]
`0.9.2` is out - thanks again for reporting the issue & for the beta testing! ;)
